### PR TITLE
Fix for missing changeset after processing from file 

### LINKED ISSUE #79: Flag : Changesets are not included
Let’s have a look at  this changeset : 
https://www.openstreetmap.org/changeset/110329853#map=10/28.2796/81.6792
it has building features 
image
But it is not included in the underpass 
image
One possible and strong reason could be of country boundary that underpass is using 
Debug Result : 
Here, This changeset i.e. 110329853 falls inside both underpass and insight boundaries. That means it should not because of boundaries that underpass is using.
image
image

### LINKED ISSUE #84: Flag: Geometry of changeset is stored as null even they have one
Let’s take this changeset as an example ,
https://www.openstreetmap.org/changeset/110814309
Can you see geometry in this changeset ? Yes I can 
But in underpass it is null
image
But if you have a look at this inside insight it has geometry : 
image
How this will affect our stat ? 
This will not affect the stat calculation that underpass is doing but the question is how we are finding whether it is inside our priority area or not ? And also when we are escaping geometry and when we will  be  providing custom polygon stat from API end it will also provide incomplete stat because this changeset doesn't have geometry in the underpass and will not be included in any polygon , These changesets will be missed in stats
More Examples : 
https://www.openstreetmap.org/changeset/110814313
https://www.openstreetmap.org/changeset/88698947
https://www.openstreetmap.org/changeset/88698950
https://www.openstreetmap.org/changeset/88698964
https://www.openstreetmap.org/changeset/88698972
And a lot more … Here is a snip from the underpass changeset table 
image
And From insight table for same changeset id 
image

### LINKED ISSUE #87: Passing Null Geometry Changeset Directly to Priority country list
Here ! 
https://github.com/hotosm/underpass/blob/8689f9a8dd61afc8c767bf5a928ddfa81a31dad8/galaxy/changeset.cc#L201-L204

### LINKED ISSUE #167: Remove changeset in table if exists after areafilter
When changeset is filtered and removed during areafilter in underpaass we need to check either that changeset row exists or not in table if it does we need to remove that row ( because that row may have processed from changefile already because in changefile we don't know where it is coming from hence it doesn't include any filteration ) , In that way we can even reduce the unwanted table size coming from changefile processing 

_Originally posted by @itskshitiz321 in https://github.com/hotosm/underpass/issues/84#issuecomment-1090067801_

### PR DESCRIPTION
**Pull request by itskshitiz321**
- Resolve #167 
- Resovle #164 
- Partially fixes #84 
- Partially fixes #79 
- Resolve #87

### CODE REVIEW

**Comment by itskshitiz321** [comment]
Still finalizing this PR  ! Opening this up as Draft to keep things in track

**Comment by robsavoye** [comment]
Why delete a row from the changesets table ? If all entries are written after areaFilter(), that should be unnecessary.  If there are bugs in areaFilter(), then yes, deleting them does some cleanup. But if we restart replicator with an empty database, this would not be required.

**Comment by itskshitiz321** [comment]
areafilter will only work while processing changeset file , I am planning to reduce the size of table when processing changefile , in Changefile we will not know where it is coming from specially when it contains modified features ! So if it is already on the table which is from changefile , I wanted to filter out those rows , because from changeset we will know where it is exactly coming from and filter out once we got changeset id , we can remove it if it is processed and inserted while processing changefile , I have commented where clause in changefile because in that we were escaping changesets which are arrived on changeset file later ! @robsavoye

**Comment by emi420** [comment]
@robsavoye @itskshitiz321 @ramyaragupathy this PR will need to be reverted because is crashing. Once is reverted I'll do a new PR with the version that we're currently running, that is the one in the following branch:

https://github.com/hotosm/underpass/tree/patch/commented-code

**Comment by itskshitiz321** [comment]
@emi420  Sure ! Sounds like a good plan

**Pull request merged**
