### PR TITLE
Fix/threading multi

### PR DESCRIPTION
**Pull request by emi420**
Option for running one thread was working but processing both osmchanges and changesets was not working.

With this fix everything is working ok for both modes.

### CODE REVIEW

**Comment by robsavoye** [comment]
There's trailing spaces. :-) Git diff against master will show them as red boxes.

**Comment by emi420** [comment]
@robsavoye I fixed the trailing space :) 

PD: I did a forced push to revert a commit/push that I made by mistake.

**Comment by robsavoye** [comment]
why put the threads into an vector ? In replicator there will only be 2 threads.

**Comment by emi420** [comment]
@robsavoye With the new optional argument for running the process only for changesets or osmchanges, there can be 1 or 2 threads.

**Pull request merged**
